services:
  pg:
    container_name: arona_paradedb
    image: paradedb/paradedb
    network_mode: host
    environment:
      POSTGRES_DB: arona
      POSTGRES_USER: plana
      POSTGRES_PASSWORD: 12345678

  dragonfly:
    container_name: arona_dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    network_mode: host
    environment:
      requirepass: 12345678
